// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.vpnproj.vpnapp.vpn

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object VpnMessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** État VPN vu par la couche Android (reflet de [VpnStatus] côté Dart). */
enum class VpnAndroidState(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTING(3),
  ERROR(4);

  companion object {
    fun ofRaw(raw: Int): VpnAndroidState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Configuration de connexion transmise à la couche native (Kotlin).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VpnConnectConfig (
  val countryCode: String,
  val serverName: String,
  val serverPort: Long? = null,
  /** Clé publique du serveur WireGuard (base64). */
  val serverPublicKey: String? = null,
  /** Endpoint du serveur WireGuard (host:port). */
  val serverEndpoint: String? = null,
  /** Clé pré-partagée optionnelle (base64). */
  val presharedKey: String? = null,
  /** IP autorisées (ex: "0.0.0.0/0"). */
  val allowedIPs: List<String>? = null,
  /** Serveur DNS (ex: "1.1.1.1"). */
  val dnsServer: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnConnectConfig {
      val countryCode = pigeonVar_list[0] as String
      val serverName = pigeonVar_list[1] as String
      val serverPort = pigeonVar_list[2] as Long?
      val serverPublicKey = pigeonVar_list[3] as String?
      val serverEndpoint = pigeonVar_list[4] as String?
      val presharedKey = pigeonVar_list[5] as String?
      val allowedIPs = pigeonVar_list[6] as List<String>?
      val dnsServer = pigeonVar_list[7] as String?
      return VpnConnectConfig(countryCode, serverName, serverPort, serverPublicKey, serverEndpoint, presharedKey, allowedIPs, dnsServer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      countryCode,
      serverName,
      serverPort,
      serverPublicKey,
      serverEndpoint,
      presharedKey,
      allowedIPs,
      dnsServer,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnConnectConfig
    return VpnMessagesPigeonUtils.deepEquals(this.countryCode, other.countryCode) && VpnMessagesPigeonUtils.deepEquals(this.serverName, other.serverName) && VpnMessagesPigeonUtils.deepEquals(this.serverPort, other.serverPort) && VpnMessagesPigeonUtils.deepEquals(this.serverPublicKey, other.serverPublicKey) && VpnMessagesPigeonUtils.deepEquals(this.serverEndpoint, other.serverEndpoint) && VpnMessagesPigeonUtils.deepEquals(this.presharedKey, other.presharedKey) && VpnMessagesPigeonUtils.deepEquals(this.allowedIPs, other.allowedIPs) && VpnMessagesPigeonUtils.deepEquals(this.dnsServer, other.dnsServer)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.countryCode)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.serverName)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.serverPort)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.serverPublicKey)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.serverEndpoint)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.presharedKey)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.allowedIPs)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.dnsServer)
    return result
  }
  override fun toString(): String {
    return "VpnConnectConfig(countryCode=$countryCode, serverName=$serverName, serverPort=$serverPort, serverPublicKey=$serverPublicKey, serverEndpoint=$serverEndpoint, presharedKey=$presharedKey, allowedIPs=$allowedIPs, dnsServer=$dnsServer)"
  }
}

/**
 * Résultat d'un appel [VpnHostApi.connect].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VpnConnectResult (
  val success: Boolean,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnConnectResult {
      val success = pigeonVar_list[0] as Boolean
      val message = pigeonVar_list[1] as String?
      return VpnConnectResult(success, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnConnectResult
    return VpnMessagesPigeonUtils.deepEquals(this.success, other.success) && VpnMessagesPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.success)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "VpnConnectResult(success=$success, message=$message)"
  }
}

/**
 * Événement d'état envoyé par le natif (Kotlin) vers Flutter.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VpnStatusEvent (
  val state: VpnAndroidState,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnStatusEvent {
      val state = pigeonVar_list[0] as VpnAndroidState
      val message = pigeonVar_list[1] as String?
      return VpnStatusEvent(state, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnStatusEvent
    return VpnMessagesPigeonUtils.deepEquals(this.state, other.state) && VpnMessagesPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "VpnStatusEvent(state=$state, message=$message)"
  }
}

/**
 * Configuration WireGuard complète retournée par le natif.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WireGuardTunnelConfig (
  val clientPrivateKey: String,
  val clientPublicKey: String,
  val clientAddress: String,
  val serverPublicKey: String,
  val serverEndpoint: String,
  val presharedKey: String? = null,
  val allowedIPs: List<String>? = null,
  val dnsServer: String? = null,
  val mtu: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WireGuardTunnelConfig {
      val clientPrivateKey = pigeonVar_list[0] as String
      val clientPublicKey = pigeonVar_list[1] as String
      val clientAddress = pigeonVar_list[2] as String
      val serverPublicKey = pigeonVar_list[3] as String
      val serverEndpoint = pigeonVar_list[4] as String
      val presharedKey = pigeonVar_list[5] as String?
      val allowedIPs = pigeonVar_list[6] as List<String>?
      val dnsServer = pigeonVar_list[7] as String?
      val mtu = pigeonVar_list[8] as Long?
      return WireGuardTunnelConfig(clientPrivateKey, clientPublicKey, clientAddress, serverPublicKey, serverEndpoint, presharedKey, allowedIPs, dnsServer, mtu)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientPrivateKey,
      clientPublicKey,
      clientAddress,
      serverPublicKey,
      serverEndpoint,
      presharedKey,
      allowedIPs,
      dnsServer,
      mtu,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WireGuardTunnelConfig
    return VpnMessagesPigeonUtils.deepEquals(this.clientPrivateKey, other.clientPrivateKey) && VpnMessagesPigeonUtils.deepEquals(this.clientPublicKey, other.clientPublicKey) && VpnMessagesPigeonUtils.deepEquals(this.clientAddress, other.clientAddress) && VpnMessagesPigeonUtils.deepEquals(this.serverPublicKey, other.serverPublicKey) && VpnMessagesPigeonUtils.deepEquals(this.serverEndpoint, other.serverEndpoint) && VpnMessagesPigeonUtils.deepEquals(this.presharedKey, other.presharedKey) && VpnMessagesPigeonUtils.deepEquals(this.allowedIPs, other.allowedIPs) && VpnMessagesPigeonUtils.deepEquals(this.dnsServer, other.dnsServer) && VpnMessagesPigeonUtils.deepEquals(this.mtu, other.mtu)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.clientPrivateKey)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.clientPublicKey)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.clientAddress)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.serverPublicKey)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.serverEndpoint)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.presharedKey)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.allowedIPs)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.dnsServer)
    result = 31 * result + VpnMessagesPigeonUtils.deepHash(this.mtu)
    return result
  }
  override fun toString(): String {
    return "WireGuardTunnelConfig(clientPrivateKey=$clientPrivateKey, clientPublicKey=$clientPublicKey, clientAddress=$clientAddress, serverPublicKey=$serverPublicKey, serverEndpoint=$serverEndpoint, presharedKey=$presharedKey, allowedIPs=$allowedIPs, dnsServer=$dnsServer, mtu=$mtu)"
  }
}
private open class VpnMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VpnAndroidState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnConnectConfig.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnConnectResult.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnStatusEvent.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WireGuardTunnelConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VpnAndroidState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is VpnConnectConfig -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is VpnConnectResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is VpnStatusEvent -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is WireGuardTunnelConfig -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val VpnMessagesPigeonMethodCodec = StandardMethodCodec(VpnMessagesPigeonCodec())

/**
 * API appelée par Flutter vers le natif (Kotlin).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface VpnHostApi {
  fun connect(config: VpnConnectConfig): VpnConnectResult
  fun disconnect()
  /** Génère une paire de clés WireGuard et retourne la config tunnel. */
  fun generateWireGuardConfig(config: VpnConnectConfig): WireGuardTunnelConfig

  companion object {
    /** The codec used by VpnHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      VpnMessagesPigeonCodec()
    }
    /** Sets up an instance of `VpnHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VpnHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpnapp.VpnHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as VpnConnectConfig
            val wrapped: List<Any?> = try {
              listOf(api.connect(configArg))
            } catch (exception: Throwable) {
              VpnMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpnapp.VpnHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disconnect()
              listOf(null)
            } catch (exception: Throwable) {
              VpnMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpnapp.VpnHostApi.generateWireGuardConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as VpnConnectConfig
            val wrapped: List<Any?> = try {
              listOf(api.generateWireGuardConfig(configArg))
            } catch (exception: Throwable) {
              VpnMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class VpnMessagesPigeonStreamHandler<T>(
    val wrapper: VpnMessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface VpnMessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/**
 * Canal d'événements : le natif (Kotlin) pousse les changements d'état
 * vers Flutter sous forme de [Stream].
 */
abstract class StatusEventsStreamHandler : VpnMessagesPigeonEventChannelWrapper<VpnStatusEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StatusEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.vpnapp.VpnEventsApi.statusEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = VpnMessagesPigeonStreamHandler<VpnStatusEvent>(streamHandler)
      EventChannel(messenger, channelName, VpnMessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from VpnMessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<VpnStatusEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
