// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// État VPN vu par la couche Android (reflet de [VpnStatus] côté Dart).
enum VpnAndroidState {
  disconnected,
  connecting,
  connected,
  disconnecting,
  error,
}

/// Configuration de connexion transmise à la couche native (Kotlin).
class VpnConnectConfig {
  VpnConnectConfig({
    required this.countryCode,
    required this.serverName,
    this.serverPort,
    this.serverPublicKey,
    this.serverEndpoint,
    this.presharedKey,
    this.allowedIPs,
    this.dnsServer,
  });

  String countryCode;

  String serverName;

  int? serverPort;

  /// Clé publique du serveur WireGuard (base64).
  String? serverPublicKey;

  /// Endpoint du serveur WireGuard (host:port).
  String? serverEndpoint;

  /// Clé pré-partagée optionnelle (base64).
  String? presharedKey;

  /// IP autorisées (ex: "0.0.0.0/0").
  List<String>? allowedIPs;

  /// Serveur DNS (ex: "1.1.1.1").
  String? dnsServer;

  List<Object?> _toList() {
    return <Object?>[
      countryCode,
      serverName,
      serverPort,
      serverPublicKey,
      serverEndpoint,
      presharedKey,
      allowedIPs,
      dnsServer,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnConnectConfig decode(Object result) {
    result as List<Object?>;
    return VpnConnectConfig(
      countryCode: result[0]! as String,
      serverName: result[1]! as String,
      serverPort: result[2] as int?,
      serverPublicKey: result[3] as String?,
      serverEndpoint: result[4] as String?,
      presharedKey: result[5] as String?,
      allowedIPs: (result[6] as List<Object?>?)?.cast<String>(),
      dnsServer: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnConnectConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(countryCode, other.countryCode) && _deepEquals(serverName, other.serverName) && _deepEquals(serverPort, other.serverPort) && _deepEquals(serverPublicKey, other.serverPublicKey) && _deepEquals(serverEndpoint, other.serverEndpoint) && _deepEquals(presharedKey, other.presharedKey) && _deepEquals(allowedIPs, other.allowedIPs) && _deepEquals(dnsServer, other.dnsServer);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VpnConnectConfig(countryCode: $countryCode, serverName: $serverName, serverPort: $serverPort, serverPublicKey: $serverPublicKey, serverEndpoint: $serverEndpoint, presharedKey: $presharedKey, allowedIPs: $allowedIPs, dnsServer: $dnsServer)';
  }
}

/// Résultat d'un appel [VpnHostApi.connect].
class VpnConnectResult {
  VpnConnectResult({
    required this.success,
    this.message,
  });

  bool success;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      success,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnConnectResult decode(Object result) {
    result as List<Object?>;
    return VpnConnectResult(
      success: result[0]! as bool,
      message: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnConnectResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(success, other.success) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VpnConnectResult(success: $success, message: $message)';
  }
}

/// Événement d'état envoyé par le natif (Kotlin) vers Flutter.
class VpnStatusEvent {
  VpnStatusEvent({
    required this.state,
    this.message,
  });

  VpnAndroidState state;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      state,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnStatusEvent decode(Object result) {
    result as List<Object?>;
    return VpnStatusEvent(
      state: result[0]! as VpnAndroidState,
      message: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnStatusEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VpnStatusEvent(state: $state, message: $message)';
  }
}

/// Configuration WireGuard complète retournée par le natif.
class WireGuardTunnelConfig {
  WireGuardTunnelConfig({
    required this.clientPrivateKey,
    required this.clientPublicKey,
    required this.clientAddress,
    required this.serverPublicKey,
    required this.serverEndpoint,
    this.presharedKey,
    this.allowedIPs,
    this.dnsServer,
    this.mtu,
  });

  String clientPrivateKey;

  String clientPublicKey;

  String clientAddress;

  String serverPublicKey;

  String serverEndpoint;

  String? presharedKey;

  List<String>? allowedIPs;

  String? dnsServer;

  int? mtu;

  List<Object?> _toList() {
    return <Object?>[
      clientPrivateKey,
      clientPublicKey,
      clientAddress,
      serverPublicKey,
      serverEndpoint,
      presharedKey,
      allowedIPs,
      dnsServer,
      mtu,
    ];
  }

  Object encode() {
    return _toList();  }

  static WireGuardTunnelConfig decode(Object result) {
    result as List<Object?>;
    return WireGuardTunnelConfig(
      clientPrivateKey: result[0]! as String,
      clientPublicKey: result[1]! as String,
      clientAddress: result[2]! as String,
      serverPublicKey: result[3]! as String,
      serverEndpoint: result[4]! as String,
      presharedKey: result[5] as String?,
      allowedIPs: (result[6] as List<Object?>?)?.cast<String>(),
      dnsServer: result[7] as String?,
      mtu: result[8] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WireGuardTunnelConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(clientPrivateKey, other.clientPrivateKey) && _deepEquals(clientPublicKey, other.clientPublicKey) && _deepEquals(clientAddress, other.clientAddress) && _deepEquals(serverPublicKey, other.serverPublicKey) && _deepEquals(serverEndpoint, other.serverEndpoint) && _deepEquals(presharedKey, other.presharedKey) && _deepEquals(allowedIPs, other.allowedIPs) && _deepEquals(dnsServer, other.dnsServer) && _deepEquals(mtu, other.mtu);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WireGuardTunnelConfig(clientPrivateKey: $clientPrivateKey, clientPublicKey: $clientPublicKey, clientAddress: $clientAddress, serverPublicKey: $serverPublicKey, serverEndpoint: $serverEndpoint, presharedKey: $presharedKey, allowedIPs: $allowedIPs, dnsServer: $dnsServer, mtu: $mtu)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is VpnAndroidState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is VpnConnectConfig) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is VpnConnectResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is VpnStatusEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is WireGuardTunnelConfig) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : VpnAndroidState.values[value];
      case 130:
        return VpnConnectConfig.decode(readValue(buffer)!);
      case 131:
        return VpnConnectResult.decode(readValue(buffer)!);
      case 132:
        return VpnStatusEvent.decode(readValue(buffer)!);
      case 133:
        return WireGuardTunnelConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// API appelée par Flutter vers le natif (Kotlin).
class VpnHostApi {
  /// Constructor for [VpnHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VpnHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<VpnConnectResult> connect(VpnConnectConfig config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpnapp.VpnHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VpnConnectResult;
  }

  Future<void> disconnect() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpnapp.VpnHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Génère une paire de clés WireGuard et retourne la config tunnel.
  Future<WireGuardTunnelConfig> generateWireGuardConfig(VpnConnectConfig config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpnapp.VpnHostApi.generateWireGuardConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as WireGuardTunnelConfig;
  }
}

/// Canal d'événements : le natif (Kotlin) pousse les changements d'état
/// vers Flutter sous forme de [Stream].
/// Returns a broadcast [Stream] of events from the `statusEvents` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<VpnStatusEvent> statusEvents( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel statusEventsChannel =
      EventChannel('dev.flutter.pigeon.vpnapp.VpnEventsApi.statusEvents$instanceName', pigeonMethodCodec);
  return statusEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as VpnStatusEvent;
  });
}
    
